openapi: 3.0.3
info:
  title: Backend Management API
  version: 0.5.5
  description: Minimal backend API for participant catalog and contract agreement retirements
servers:
  - url: /
  - url: http://localhost:8080
paths:
  /catalog/participantCatalog:
    get:
      summary: Get participant catalog
      description: Retrieves the participant's own catalog
      operationId: participantcatalog
      tags:
        - management-api
      responses:
        '200':
          description: The participant's catalog
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '400':
          description: Request was malformed
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
  /v3/contractagreements/retirements:
    post:
      description: Retires an active contract agreement.
      operationId: retireAgreementV3
      tags:
        - management-api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RetirementRequest'
      responses:
        '204':
          description: The contract agreement was successfully retired
        '400':
          description: Request body was malformed
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
        '409':
          description: The contract agreement is already retired
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
  /v3/contractagreements/retirements/request:
    post:
      description: Get all retired contract agreements.
      operationId: getAllRetiredV3
      tags:
        - management-api
      responses:
        '200':
          description: A list of retired contract agreements
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        '400':
          description: Request body was malformed
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
  /v3/contractagreements/retirements/{agreementId}:
    delete:
      description: Removes a contract agreement from the retired list, reactivating it.
      operationId: reactivateRetiredV3
      tags:
        - management-api
      parameters:
        - name: agreementId
          in: path
          description: The contract agreement id
          required: true
          schema:
            type: string
      responses:
        '204':
          description: The contract agreement is reactivated
        '400':
          description: Request body was malformed
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
        '404':
          description: No entry for the given agreementId was found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiErrorDetail'
components:
  schemas:
    ApiErrorDetail:
      type: object
      properties:
        invalidValue:
          type: string
        message:
          type: string
        path:
          type: string
        type:
          type: string
      example:
        message: error message
        type: ErrorType
        path: object.error.path
        invalidValue: this value is not valid
    RetirementRequest:
      type: object
      properties:
        '@id':
          type: string
        reason:
          type: string
tags:
  - name: management-api
    description: REST API documentation for the management-api
security: []
