export * from './assetV3.service';
import { AssetV3Service } from './assetV3.service';
export * from './assetV4alpha.service';
import { AssetV4alphaService } from './assetV4alpha.service';
export * from './catalogV3.service';
import { CatalogV3Service } from './catalogV3.service';
export * from './catalogV4alpha.service';
import { CatalogV4alphaService } from './catalogV4alpha.service';
export * from './contractAgreementV3.service';
import { ContractAgreementV3Service } from './contractAgreementV3.service';
export * from './contractAgreementV4alpha.service';
import { ContractAgreementV4alphaService } from './contractAgreementV4alpha.service';
export * from './contractDefinitionV3.service';
import { ContractDefinitionV3Service } from './contractDefinitionV3.service';
export * from './contractDefinitionV4alpha.service';
import { ContractDefinitionV4alphaService } from './contractDefinitionV4alpha.service';
export * from './contractNegotiationV3.service';
import { ContractNegotiationV3Service } from './contractNegotiationV3.service';
export * from './contractNegotiationV4alpha.service';
import { ContractNegotiationV4alphaService } from './contractNegotiationV4alpha.service';
export * from './dataplaneSelectorV3.service';
import { DataplaneSelectorV3Service } from './dataplaneSelectorV3.service';
export * from './dataplaneSelectorV4alpha.service';
import { DataplaneSelectorV4alphaService } from './dataplaneSelectorV4alpha.service';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './eDRCacheV3.service';
import { EDRCacheV3Service } from './eDRCacheV3.service';
export * from './eDRCacheV4alpha.service';
import { EDRCacheV4alphaService } from './eDRCacheV4alpha.service';
export * from './hTTPProvisionerWebhook.service';
import { HTTPProvisionerWebhookService } from './hTTPProvisionerWebhook.service';
export * from './policyDefinitionV3.service';
import { PolicyDefinitionV3Service } from './policyDefinitionV3.service';
export * from './policyDefinitionV4alpha.service';
import { PolicyDefinitionV4alphaService } from './policyDefinitionV4alpha.service';
export * from './secretV3.service';
import { SecretV3Service } from './secretV3.service';
export * from './secretV4alpha.service';
import { SecretV4alphaService } from './secretV4alpha.service';
export * from './transferProcessV3.service';
import { TransferProcessV3Service } from './transferProcessV3.service';
export * from './transferProcessV4alpha.service';
import { TransferProcessV4alphaService } from './transferProcessV4alpha.service';
export const APIS = [AssetV3Service, AssetV4alphaService, CatalogV3Service, CatalogV4alphaService, ContractAgreementV3Service, ContractAgreementV4alphaService, ContractDefinitionV3Service, ContractDefinitionV4alphaService, ContractNegotiationV3Service, ContractNegotiationV4alphaService, DataplaneSelectorV3Service, DataplaneSelectorV4alphaService, DefaultService, EDRCacheV3Service, EDRCacheV4alphaService, HTTPProvisionerWebhookService, PolicyDefinitionV3Service, PolicyDefinitionV4alphaService, SecretV3Service, SecretV4alphaService, TransferProcessV3Service, TransferProcessV4alphaService];
