/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuerySpec } from './querySpec';


export interface CatalogRequest {
    '@context': object;
    '@type'?: string;
    additionalScopes?: Array<string>;
    counterPartyAddress: string;
    counterPartyId?: string;
    protocol: string;
    querySpec?: QuerySpec;
}

