/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Criterion } from './criterion';


export interface ContractDefinitionOutput {
    '@id'?: string;
    '@type'?: string;
    accessPolicyId?: string;
    assetsSelector?: Array<Criterion>;
    contractPolicyId?: string;
    createdAt?: number;
}

