/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Offer } from './offer';
import { CallbackAddress } from './callbackAddress';


export interface ContractRequest {
    '@context': object;
    '@type'?: string;
    callbackAddresses?: Array<CallbackAddress>;
    counterPartyAddress: string;
    policy: Offer;
    protocol: string;
}

