/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MappingDefinition } from './mappingDefinition';
import { CredentialRuleDefinition } from './credentialRuleDefinition';


export interface CredentialDefinition {
    attestations?: Array<string>;
    credentialType?: string;
    formats?: Set<CredentialDefinition.FormatsEnum>;
    id?: string;
    jsonSchema?: string;
    jsonSchemaUrl?: string;
    mappings?: Array<MappingDefinition>;
    participantContextId?: string;
    rules?: Array<CredentialRuleDefinition>;
    validity?: number;
}
export namespace CredentialDefinition {
    export type FormatsEnum = 'JSON_LD' | 'JWT' | 'VC1_0_LD' | 'VC1_0_JWT' | 'VC2_0_JOSE' | 'VC2_0_SD_JWT' | 'VC2_0_COSE';
    export const FormatsEnum = {
        JsonLd: 'JSON_LD' as FormatsEnum,
        Jwt: 'JWT' as FormatsEnum,
        Vc10Ld: 'VC1_0_LD' as FormatsEnum,
        Vc10Jwt: 'VC1_0_JWT' as FormatsEnum,
        Vc20Jose: 'VC2_0_JOSE' as FormatsEnum,
        Vc20SdJwt: 'VC2_0_SD_JWT' as FormatsEnum,
        Vc20Cose: 'VC2_0_COSE' as FormatsEnum
    };
}


