/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DataPlaneInstanceSchema {
    '@context': object;
    '@id'?: string;
    '@type'?: string;
    allowedDestTypes: Set<string>;
    allowedSourceTypes: Set<string>;
    lastActive?: number;
    state?: string;
    stateTimestamp?: number;
    turnCount?: number;
    url: string;
}

