/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VerificationMethod } from './verificationMethod';
import { Service } from './service';


export interface DidDocument {
    '@context'?: Array<object>;
    authentication?: Array<string>;
    id?: string;
    service?: Array<Service>;
    verificationMethod?: Array<VerificationMethod>;
}

