/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Action } from './action';
import { Constraint } from './constraint';


export interface Duty {
    action?: Action;
    constraints?: Array<Constraint>;
}

