/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HolderDto {
    did: string;
    holderId: string;
    name?: string;
}

