/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface HolderCredentialRequestDto {
    holderPid?: string;
    issuerDid?: string;
    issuerPid?: string;
    status?: string;
    typesAndFormats?: { [key: string]: string; };
}

