/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IdentityApiKeyPairResource {
    defaultPair?: boolean;
    groupName?: string;
    id?: string;
    keyContext?: string;
    keyId?: string;
    participantContextId?: string;
    privateKeyAlias?: string;
    rotationDuration?: number;
    serializedPublicKey?: string;
    state?: number;
    timestamp?: number;
    useDuration?: number;
}

