/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { KeyDescriptor } from './keyDescriptor';
import { Service } from './service';


export interface IdentityApiParticipantManifest {
    active?: boolean;
    additionalProperties?: { [key: string]: object; };
    did?: string;
    key?: KeyDescriptor;
    participantId?: string;
    roles?: Array<string>;
    serviceEndpoints?: Set<Service>;
}

