/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IdentityApiKeyDescriptor {
    active?: boolean;
    keyGeneratorParams?: { [key: string]: object; };
    keyId?: string;
    privateKeyAlias?: string;
    publicKeyJwk?: { [key: string]: object; };
    publicKeyPem?: string;
    resourceId?: string;
    type?: string;
}

