/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CredentialSubject } from './credentialSubject';
import { CredentialStatus } from './credentialStatus';
import { Issuer } from './issuer';
import { CredentialSchema } from './credentialSchema';


export interface IdentityApiVerifiableCredential {
    credentialSchema?: Array<CredentialSchema>;
    credentialStatus?: Array<CredentialStatus>;
    credentialSubject?: Array<CredentialSubject>;
    dataModelVersion?: IdentityApiVerifiableCredential.DataModelVersionEnum;
    description?: string;
    expirationDate?: string;
    id?: string;
    issuanceDate?: string;
    issuer?: Issuer;
    name?: string;
    type?: Array<string>;
}
export namespace IdentityApiVerifiableCredential {
    export type DataModelVersionEnum = 'V_1_1' | 'V_2_0';
    export const DataModelVersionEnum = {
        _11: 'V_1_1' as DataModelVersionEnum,
        _20: 'V_2_0' as DataModelVersionEnum
    };
}


