/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Prohibition } from './prohibition';
import { Duty } from './duty';
import { Permission } from './permission';


export interface IdentityApiPolicy {
    '@type'?: IdentityApiPolicy.TypeEnum;
    assignee?: string;
    assigner?: string;
    extensibleProperties?: { [key: string]: object; };
    inheritsFrom?: string;
    obligations?: Array<Duty>;
    permissions?: Array<Permission>;
    profiles?: Array<string>;
    prohibitions?: Array<Prohibition>;
    target?: string;
}
export namespace IdentityApiPolicy {
    export type TypeEnum = 'SET' | 'OFFER' | 'CONTRACT';
    export const TypeEnum = {
        Set: 'SET' as TypeEnum,
        Offer: 'OFFER' as TypeEnum,
        Contract: 'CONTRACT' as TypeEnum
    };
}


