/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CredentialDescriptor } from './credentialDescriptor';


export interface IdentityApiCredentialRequestDto {
    credentials: Array<CredentialDescriptor>;
    holderPid?: string;
    issuerDid: string;
}

