/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VerifiableCredential } from './verifiableCredential';


export interface IssuerAdminApiVerifiableCredentialDto {
    credential?: VerifiableCredential;
    format?: IssuerAdminApiVerifiableCredentialDto.FormatEnum;
    participantContextId?: string;
}
export namespace IssuerAdminApiVerifiableCredentialDto {
    export type FormatEnum = 'JSON_LD' | 'JWT' | 'VC1_0_LD' | 'VC1_0_JWT' | 'VC2_0_JOSE' | 'VC2_0_SD_JWT' | 'VC2_0_COSE';
    export const FormatEnum = {
        JsonLd: 'JSON_LD' as FormatEnum,
        Jwt: 'JWT' as FormatEnum,
        Vc10Ld: 'VC1_0_LD' as FormatEnum,
        Vc10Jwt: 'VC1_0_JWT' as FormatEnum,
        Vc20Jose: 'VC2_0_JOSE' as FormatEnum,
        Vc20SdJwt: 'VC2_0_SD_JWT' as FormatEnum,
        Vc20Cose: 'VC2_0_COSE' as FormatEnum
    };
}


