/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MappingDefinition } from './mappingDefinition';
import { CredentialRuleDefinition } from './credentialRuleDefinition';


export interface IssuerAdminApiCredentialDefinitionDto {
    attestations?: Array<string>;
    credentialType?: string;
    formats?: Set<string>;
    id?: string;
    jsonSchema?: string;
    jsonSchemaUrl?: string;
    mappings?: Array<MappingDefinition>;
    rules?: Array<CredentialRuleDefinition>;
    validity?: number;
}

