/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IssuerAdminApiIssuanceProcessDto {
    claims?: { [key: string]: object; };
    createdAt?: number;
    credentialDefinitions?: Array<string>;
    credentialFormats?: { [key: string]: string; };
    holderId?: string;
    holderPid?: string;
    id?: string;
    participantContextId?: string;
    state?: string;
    updatedAt?: number;
}
export namespace IssuerAdminApiIssuanceProcessDto {
    export type CredentialFormatsEnum = 'JSON_LD' | 'JWT' | 'VC1_0_LD' | 'VC1_0_JWT' | 'VC2_0_JOSE' | 'VC2_0_SD_JWT' | 'VC2_0_COSE';
    export const CredentialFormatsEnum = {
        JsonLd: 'JSON_LD' as CredentialFormatsEnum,
        Jwt: 'JWT' as CredentialFormatsEnum,
        Vc10Ld: 'VC1_0_LD' as CredentialFormatsEnum,
        Vc10Jwt: 'VC1_0_JWT' as CredentialFormatsEnum,
        Vc20Jose: 'VC2_0_JOSE' as CredentialFormatsEnum,
        Vc20SdJwt: 'VC2_0_SD_JWT' as CredentialFormatsEnum,
        Vc20Cose: 'VC2_0_COSE' as CredentialFormatsEnum
    };
}


