/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface IssuerAdminApiAttestationDefinitionRequest {
    attestationType?: string;
    configuration?: { [key: string]: object; };
    id?: string;
}

