/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JsonValue } from './jsonValue';


export interface JsonObject {
  [key: string]: JsonValue | any;


    empty?: boolean;
    valueType?: JsonObject.ValueTypeEnum;
}
export namespace JsonObject {
    export type ValueTypeEnum = 'ARRAY' | 'OBJECT' | 'STRING' | 'NUMBER' | 'TRUE' | 'FALSE' | 'NULL';
    export const ValueTypeEnum = {
        Array: 'ARRAY' as ValueTypeEnum,
        Object: 'OBJECT' as ValueTypeEnum,
        String: 'STRING' as ValueTypeEnum,
        Number: 'NUMBER' as ValueTypeEnum,
        True: 'TRUE' as ValueTypeEnum,
        False: 'FALSE' as ValueTypeEnum,
        Null: 'NULL' as ValueTypeEnum
    };
}


