/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ODRL offer
 */
export interface Offer {
    '@id': string;
    '@type'?: string;
    assigner: string;
    target: string;
}

