/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ParticipantContext {
    apiTokenAlias?: string;
    createdAt?: number;
    did?: string;
    lastModified?: number;
    participantContextId?: string;
    properties?: { [key: string]: object; };
    roles?: Array<string>;
    state?: number;
}

