/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Action } from './action';
import { Constraint } from './constraint';
import { Duty } from './duty';


export interface Permission {
    action?: Action;
    constraints?: Array<Constraint>;
    duties?: Array<Duty>;
}

