/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PresentationResponseMessagePresentationInner } from './presentationResponseMessagePresentationInner';


export interface PresentationResponseMessage {
    '@context': object;
    presentation: Array<PresentationResponseMessagePresentationInner>;
}

