/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PresentationQueryMessage {
    '@context': object;
    '@type': string;
    presentationDefinition?: object;
    scope?: Array<string>;
}

