/**
 * Backend Management API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RetirementRequest {
    '@id'?: string;
    reason?: string;
}

