/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataAddress } from './dataAddress';


export interface SelectionRequestSchema {
    '@type'?: string;
    destination?: DataAddress;
    source?: DataAddress;
    strategy?: string;
    transferType?: string;
}

