/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CallbackAddress } from './callbackAddress';
import { DataAddress } from './dataAddress';


export interface TransferRequest {
    '@context': object;
    '@type'?: string;
    /** @deprecated */
    assetId?: string;
    callbackAddresses?: Array<CallbackAddress>;
    contractId: string;
    counterPartyAddress: string;
    dataDestination?: DataAddress;
    privateProperties?: object;
    protocol: string;
    transferType: string;
}

