/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VerifiableCredentialContainer } from './verifiableCredentialContainer';


export interface VerifiableCredentialManifest {
    id?: string;
    /**
     * ODRL policy
     */
    issuancePolicy?: object;
    participantContextId?: string;
    /**
     * ODRL policy
     */
    reissuancePolicy?: object;
    verifiableCredentialContainer?: VerifiableCredentialContainer;
}

