/**
 * Complete API Specification
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VerifiableCredentialContainer } from './verifiableCredentialContainer';


export interface VerifiableCredentialResource {
    credentialStatus?: VerifiableCredentialResource.CredentialStatusEnum;
    holderId?: string;
    id?: string;
    /**
     * ODRL policy
     */
    issuancePolicy?: object;
    issuerId?: string;
    metadata?: { [key: string]: object; };
    participantContextId?: string;
    /**
     * ODRL policy
     */
    reissuancePolicy?: object;
    state?: number;
    timeOfLastStatusUpdate?: string;
    timestamp?: number;
    verifiableCredential?: VerifiableCredentialContainer;
}
export namespace VerifiableCredentialResource {
    export type CredentialStatusEnum = 'INITIAL' | 'REQUESTING' | 'REQUESTED' | 'ISSUING' | 'ISSUED' | 'REVOKED' | 'SUSPENDED' | 'EXPIRED' | 'NOT_YET_VALID' | 'ERROR';
    export const CredentialStatusEnum = {
        Initial: 'INITIAL' as CredentialStatusEnum,
        Requesting: 'REQUESTING' as CredentialStatusEnum,
        Requested: 'REQUESTED' as CredentialStatusEnum,
        Issuing: 'ISSUING' as CredentialStatusEnum,
        Issued: 'ISSUED' as CredentialStatusEnum,
        Revoked: 'REVOKED' as CredentialStatusEnum,
        Suspended: 'SUSPENDED' as CredentialStatusEnum,
        Expired: 'EXPIRED' as CredentialStatusEnum,
        NotYetValid: 'NOT_YET_VALID' as CredentialStatusEnum,
        Error: 'ERROR' as CredentialStatusEnum
    };
}


