/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataAddressSchema } from './dataAddressSchema';


export interface AssetSchema { 
    '@context': Array<string>;
    '@type': string;
    '@id'?: string;
    properties: object;
    privateProperties?: object;
    dataAddress: DataAddressSchema;
}

