/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataAddress } from './dataAddress';


export interface AssetInputV3 { 
    '@context': object;
    '@id'?: string;
    '@type'?: string;
    dataAddress: DataAddress;
    privateProperties?: object;
    properties: object;
}

