/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataAddress } from './dataAddress';


export interface AssetOutputV3 { 
    '@id'?: string;
    '@type'?: string;
    createdAt?: number;
    dataAddress?: DataAddress;
    privateProperties?: object;
    properties?: object;
}

