/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AtomicConstraintStep { 
    '@type': string;
    isFiltered?: boolean;
    filteringReasons?: Array<string>;
    functionName?: string;
    functionParams?: Array<string>;
}

