/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Operator } from './operator';
import { RightOperand } from './rightOperand';


export interface AtomicConstraint { 
    rightOperand: RightOperand;
    leftOperand: string;
    operator: Operator;
}
export namespace AtomicConstraint {
}


