/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CallbackAddressSchema { 
    '@type': string;
    transactional: boolean;
    uri: string;
    events: Array<string>;
    authKey?: string;
    authCodeId?: string;
}

