/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CallbackAddress { 
    '@type'?: string;
    authCodeId?: string;
    authKey?: string;
    events?: Set<string>;
    transactional?: boolean;
    uri?: string;
}

