/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuerySpec } from './querySpec';


export interface CatalogRequest { 
    '@context': Array<string>;
    '@type': string;
    '@id'?: string;
    protocol: string;
    counterPartyAddress: string;
    counterPartyId: string;
    additionalScopes?: Array<string>;
    querySpec?: QuerySpec;
}

