/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Operator } from './operator';
import { AtomicConstraint } from './atomicConstraint';
import { RightOperand } from './rightOperand';
import { LogicalConstraint } from './logicalConstraint';


/**
 * @type Constraint
 * @export
 */
export type Constraint = AtomicConstraint | LogicalConstraint;

