/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AndConstraintStep } from './andConstraintStep';
import { OrConstraintStep } from './orConstraintStep';
import { AtomicConstraintStep } from './atomicConstraintStep';
import { XoneConstraintStep } from './xoneConstraintStep';


/**
 * @type ConstraintStep
 * @export
 */
export type ConstraintStep = AndConstraintStep | AtomicConstraintStep | OrConstraintStep | XoneConstraintStep;

