/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CallbackAddress } from './callbackAddress';
import { OfferV3 } from './offerV3';


export interface ContractRequestV3 { 
    '@context': object;
    '@type'?: string;
    callbackAddresses?: Array<CallbackAddress>;
    counterPartyAddress: string;
    policy: OfferV3;
    protocol: string;
}

