/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CallbackAddressSchema } from './callbackAddressSchema';


export interface ContractNegotiationSchema { 
    '@context': Array<string>;
    '@type': string;
    '@id': string;
    type: ContractNegotiationSchema.TypeEnum;
    state: string;
    stateTimestamp?: number;
    protocol: string;
    createdAt: number;
    callbackAddresses?: Array<CallbackAddressSchema>;
    counterPartyAddress: string;
    counterPartyId: string;
    errorDetail?: string;
    correlationId?: string;
    assetId?: string;
    contractAgreementId?: string;
}
export namespace ContractNegotiationSchema {
    export type TypeEnum = 'CONSUMER' | 'PROVIDER';
    export const TypeEnum = {
        Consumer: 'CONSUMER' as TypeEnum,
        Provider: 'PROVIDER' as TypeEnum
    };
}


