/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Criterion1 } from './criterion1';


export interface ContractDefinitionInputV3 { 
    '@context': object;
    '@id'?: string;
    '@type'?: string;
    accessPolicyId: string;
    assetsSelector: Array<Criterion1>;
    contractPolicyId: string;
}

