/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CallbackAddressSchema } from './callbackAddressSchema';
import { ContractOfferSchema } from './contractOfferSchema';


export interface ContractRequest { 
    '@context': Array<string>;
    '@type': string;
    '@id'?: string;
    counterPartyAddress: string;
    protocol: string;
    policy: ContractOfferSchema;
    callbackAddresses?: Array<CallbackAddressSchema>;
}

