/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ContractAgreement1 { 
    '@id'?: string;
    '@type'?: string;
    assetId?: string;
    consumerId?: string;
    contractSigningDate?: number;
    /**
     * ODRL policy
     */
    policy?: object;
    providerId?: string;
}

