/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CallbackAddress } from './callbackAddress';


export interface ContractNegotiation { 
    '@id'?: string;
    '@type'?: string;
    callbackAddresses?: Array<CallbackAddress>;
    contractAgreementId?: string;
    counterPartyAddress?: string;
    counterPartyId?: string;
    errorDetail?: string;
    protocol?: string;
    state?: string;
    type?: ContractNegotiation.TypeEnum;
}
export namespace ContractNegotiation {
    export type TypeEnum = 'CONSUMER' | 'PROVIDER';
    export const TypeEnum = {
        Consumer: 'CONSUMER' as TypeEnum,
        Provider: 'PROVIDER' as TypeEnum
    };
}


