/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Prohibition } from './prohibition';
import { PolicyClassProfile } from './policyClassProfile';
import { Duty } from './duty';
import { Permission } from './permission';


export interface ContractOffer { 
    '@id': string;
    profile?: PolicyClassProfile;
    permission?: Array<Permission>;
    prohibition?: Array<Prohibition>;
    obligation?: Array<Duty>;
    '@type': string;
    target: string;
    assigner: string;
}

