/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Criterion } from './criterion';


export interface ContractDefinition { 
    '@context': Array<string>;
    '@type': string;
    '@id'?: string;
    accessPolicyId: string;
    contractPolicyId: string;
    privateProperties?: object;
    assetsSelector?: Array<Criterion>;
}

