/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Criterion { 
    '@type': string;
    operandLeft: string;
    operandRight: any | null;
    operator: string;
}

