/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Criterion1 { 
    '@type'?: string;
    operandLeft: object;
    operandRight: object;
    operator: string;
}

