/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Dataset } from './dataset';


export interface DataService { 
    '@id': string;
    '@type': string;
    endpointURL: string;
    servesDataset?: Array<Dataset>;
}

