/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuerySpec8 } from './querySpec8';


export interface DatasetRequestV3 { 
    '@type'?: string;
    counterPartyAddress?: string;
    counterPartyId?: string;
    protocol?: string;
    querySpec?: QuerySpec8;
}

