/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DataPlaneInstanceSchemaV3 { 
    '@context': object;
    '@id'?: string;
    '@type'?: string;
    /** @deprecated */
    allowedDestTypes: Set<string>;
    allowedSourceTypes: Set<string>;
    lastActive?: number;
    state?: string;
    stateTimestamp?: number;
    /** @deprecated */
    turnCount?: number;
    url: string;
}

