/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DeprovisionedResource { 
    error?: boolean;
    errorMessage?: string;
    inProcess?: boolean;
    provisionedResourceId?: string;
}

