/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DistributionAccessService } from './distributionAccessService';
import { Offer } from './offer';


export interface Distribution { 
    hasPolicy?: Array<Offer>;
    accessService: DistributionAccessService;
    format: string;
}

