/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Constraint } from './constraint';


export interface LogicalConstraint { 
    and?: Array<Constraint>;
    andSequence?: Array<Constraint>;
    or?: Array<Constraint>;
    xone?: Array<Constraint>;
}

