/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * ODRL offer
 */
export interface OfferV3 { 
    '@id': string;
    '@type'?: string;
    assigner: string;
    target: string;
}

