/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Operator = 'eq' | 'gt' | 'gteq' | 'lteq' | 'hasPart' | 'isA' | 'isAllOf' | 'isAnyOf' | 'isNoneOf' | 'isPartOf' | 'lt' | 'term-lteq' | 'neq';

export const Operator = {
    Eq: 'eq' as Operator,
    Gt: 'gt' as Operator,
    Gteq: 'gteq' as Operator,
    Lteq: 'lteq' as Operator,
    HasPart: 'hasPart' as Operator,
    IsA: 'isA' as Operator,
    IsAllOf: 'isAllOf' as Operator,
    IsAnyOf: 'isAnyOf' as Operator,
    IsNoneOf: 'isNoneOf' as Operator,
    IsPartOf: 'isPartOf' as Operator,
    Lt: 'lt' as Operator,
    TermLteq: 'term-lteq' as Operator,
    Neq: 'neq' as Operator
};

