/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConstraintStep } from './constraintStep';


export interface OrConstraintStep { 
    constraintSteps: Array<ConstraintStep>;
    '@type': string;
}

