/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConstraintStep } from './constraintStep';
import { DutyStep } from './dutyStep';


export interface PermissionStep { 
    isFiltered?: boolean;
    filteringReasons?: Array<string>;
    constraintSteps?: Array<ConstraintStep>;
    ruleFunctions?: Array<string>;
    '@type': string;
    dutySteps?: Array<DutyStep>;
}

