/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PolicyValidationResultSchema { 
    '@context': Array<string>;
    '@type': string;
    isValid: boolean;
    errors: Array<string>;
}

