/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PolicyClass1 } from './policyClass1';


export interface PolicyDefinition { 
    '@context': Array<string>;
    '@type': string;
    '@id'?: string;
    policy: PolicyClass1;
    privateProperties?: object;
}

