/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PermissionStep } from './permissionStep';
import { ProhibitionStep } from './prohibitionStep';
import { DutyStep } from './dutyStep';


export interface PolicyEvaluationPlan { 
    '@context': Array<string>;
    '@type': string;
    preValidators?: Array<string>;
    postValidators?: Array<string>;
    permissionSteps?: Array<PermissionStep>;
    prohibitionSteps?: Array<ProhibitionStep>;
    dutySteps?: Array<DutyStep>;
}

