/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DataAddress1 } from './dataAddress1';


export interface ProvisionerWebhookRequest { 
    apiKeyJwt?: string;
    assetId?: string;
    contentDataAddress?: DataAddress1;
    hasToken?: boolean;
    resourceDefinitionId?: string;
    resourceName?: string;
}

