/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Criterion1 } from './criterion1';


export interface QuerySpec7 { 
    '@type'?: string;
    filterExpression?: Array<Criterion1>;
    limit?: number;
    offset?: number;
    sortField?: string;
    sortOrder?: QuerySpec7.SortOrderEnum;
}
export namespace QuerySpec7 {
    export type SortOrderEnum = 'ASC' | 'DESC';
    export const SortOrderEnum = {
        Asc: 'ASC' as SortOrderEnum,
        Desc: 'DESC' as SortOrderEnum
    };
}


