/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Criterion } from './criterion';


export interface QuerySpec { 
    '@type': string;
    offset?: number;
    limit?: number;
    sortField?: string;
    sortOrder?: QuerySpec.SortOrderEnum;
    filterExpression?: Array<Criterion>;
}
export namespace QuerySpec {
    export type SortOrderEnum = 'ASC' | 'DESC';
    export const SortOrderEnum = {
        Asc: 'ASC' as SortOrderEnum,
        Desc: 'DESC' as SortOrderEnum
    };
}


