/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Offer } from './offer';
import { Distribution } from './distribution';


export interface RootDataset { 
    '@context': Array<string>;
    hasPolicy: Array<Offer>;
    '@id': string;
    distribution: Array<Distribution>;
}

