/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Dataset } from './dataset';
import { Distribution } from './distribution';
import { Catalog } from './catalog';
import { DataService } from './dataService';


export interface RootCatalog { 
    '@context': Array<string>;
    participantId: string;
    '@id': string;
    distribution?: Array<Distribution>;
    '@type': string;
    dataset?: Array<Dataset>;
    catalog?: Array<Catalog>;
    service?: Array<DataService>;
}

