/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CallbackAddress } from './callbackAddress';
import { DataAddress } from './dataAddress';


export interface TransferProcessV3 { 
    '@id'?: string;
    '@type'?: string;
    callbackAddresses?: Array<CallbackAddress>;
    contractAgreementId?: string;
    counterPartyAddress?: string;
    counterPartyId?: string;
    dataDestination?: DataAddress;
    errorDetail?: string;
    privateProperties?: object;
    protocol?: string;
    state?: string;
    type?: TransferProcessV3.TypeEnum;
}
export namespace TransferProcessV3 {
    export type TypeEnum = 'CONSUMER' | 'PROVIDER';
    export const TypeEnum = {
        Consumer: 'CONSUMER' as TypeEnum,
        Provider: 'PROVIDER' as TypeEnum
    };
}


