/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CallbackAddressSchema } from './callbackAddressSchema';
import { DataAddressSchema } from './dataAddressSchema';


export interface TransferProcess { 
    '@context': Array<string>;
    '@type': string;
    '@id': string;
    type: TransferProcess.TypeEnum;
    state: string;
    stateTimestamp: number;
    callbackAddresses?: Array<CallbackAddressSchema>;
    correlationId?: string;
    assetId?: string;
    contractId?: string;
    transferType?: string;
    errorDetail?: string;
    dataDestination?: DataAddressSchema;
}
export namespace TransferProcess {
    export type TypeEnum = 'CONSUMER' | 'PROVIDER';
    export const TypeEnum = {
        Consumer: 'CONSUMER' as TypeEnum,
        Provider: 'PROVIDER' as TypeEnum
    };
}


