/**
 * management-api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CallbackAddressSchema } from './callbackAddressSchema';
import { DataAddressSchema } from './dataAddressSchema';


export interface TransferRequest { 
    '@context': Array<string>;
    '@type': string;
    '@id'?: string;
    counterPartyAddress: string;
    protocol: string;
    contractId: string;
    transferType: string;
    privateProperties?: object;
    dataDestination?: DataAddressSchema;
    callbackAddresses?: Array<CallbackAddressSchema>;
}

